name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - uses: actions/checkout@v6
        if: ${{ steps.release.outputs.release_created }}

      - uses: oven-sh/setup-bun@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          bun-version: latest

      - run: bun install --ignore-scripts
        if: ${{ steps.release.outputs.release_created }}

      # Ensure node setup to support npm oidc publishing
      # (unsupported in bun as of 2026-03)
      - uses: actions/setup-node@v6
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      # Build from root dir to ensure types generated
      - run: |
          bun run build
          npm publish --provenance
        if: ${{ steps.release.outputs.release_created }}
